[build]
builder = "dockerfile"
dockerfilePath = "app/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
ENVIRONMENT = "production"
PORT = "8000"